# Generated by Django 4.2.28 on 2026-02-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телеграмм ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
    ]
