# Generated by Django 4.2.28 on 2026-02-22 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventModel',
            new_name='TimeEvent',
        ),
    ]
