# Generated by Django 3.2.16 on 2026-02-11 05:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', code='invalid_digists', message='Only digist')])),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('second_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('father_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('clockin', 'Приход'), ('clockout', 'Уход')], max_length=50)),
                ('time_as', models.CharField(max_length=50)),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='tg_users.telegramuser')),
            ],
        ),
    ]
