# Generated by Django 3.2.16 on 2026-01-25 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d+$', code='invalid_digists', message='Only digist'), django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='father_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='second_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
